# Generated by Django 5.2.4 on 2025-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('image', models.ImageField(upload_to='idea_images/')),
            ],
        ),
    ]
