# Generated by Django 5.2.4 on 2025-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='description',
            field=models.TextField(default='없음'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='tool',
            field=models.CharField(max_length=50),
        ),
    ]
