# Generated by Django 5.2.4 on 2025-07-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_description_alter_idea_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(verbose_name='설명없음'),
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='idea.idea')),
            ],
        ),
    ]
