# Generated by Django 5.2.4 on 2025-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
