# Generated by Django 5.2.4 on 2025-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actor',
            field=models.CharField(default='없음', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default='없음', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
